In [1]:
import pandas as pd
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt


In [2]:
torch.__version__

'2.13.0'

In [7]:
scalar=torch.tensor(10)
scalar
scalar.item()
print(type(scalar))

<class 'torch.Tensor'>


In [9]:
scalar.ndim

0

In [21]:
vector = torch.tensor([1,2,3])
print(vector)
vector.ndim
# vector.size()
# vector.rank()


tensor([1, 2, 3])


1

In [20]:
vector.shape

torch.Size([3])

In [26]:
Matrix = torch.tensor([[1,2,3],[4,5,6]])
Matrix
Matrix.ndim
Matrix.shape

torch.Size([2, 3])

In [25]:
Matrix[0][1]

tensor(2)

In [27]:
Matrix.size()

torch.Size([2, 3])

In [31]:
TENSOR = torch.tensor([[[[1,2,3],
                          [4,5,6]],
                         [[5,6,7],
                          [8,9,10]]]])
TENSOR


tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 5,  6,  7],
          [ 8,  9, 10]]]])

In [32]:
TENSOR.shape

torch.Size([1, 2, 2, 3])

In [33]:
RandomTensor = torch.rand(2,3,4)
RandomTensor

tensor([[[0.5677, 0.1002, 0.8078, 0.7963],
         [0.6999, 0.8900, 0.4911, 0.5050],
         [0.9711, 0.0583, 0.3509, 0.9325]],

        [[0.4700, 0.2342, 0.6821, 0.0923],
         [0.3473, 0.7528, 0.4408, 0.9334],
         [0.7739, 0.0415, 0.1205, 0.8488]]])

In [34]:
RandomTensor.shape

torch.Size([2, 3, 4])

In [35]:
RandomTensor.ndimension()

3

In [36]:
RandomTensor.ndim

3

In [ ]:
random_image_tensor = torch.rand(3, 224,  224)
random_image_tensor
random_image_tensor.shape

torch.Size([224, 224, 3])

In [40]:
random_image_tensor.ndim

3

In [43]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [49]:
one_to_twenty = torch.arange(0,20)
one_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [50]:
one_to_twenty.shape

torch.Size([20])

In [51]:
one_to_twenty.shape

torch.Size([20])

In [55]:
twenty_to_thirty = torch.zeros_like(one_to_twenty)
twenty_to_thirty

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
float_32 = torch.tensor([3,4,5], dtype=torch.float32, device='cpu', requires_grad=False)
print(float_32)
print(float_32.dtype)


tensor([3., 4., 5.])
torch.float32


In [62]:
float_16 = float_32.half()
print(float_16)
print(float_16.dtype)


tensor([3., 4., 5.], dtype=torch.float16)
torch.float16


In [67]:
print(torch.mul(float_16, float_32))

tensor([ 9., 16., 25.])
