In [1]:
import pandas as pd
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt


In [2]:
torch.__version__

'2.13.0+cu130'

In [3]:
scalar=torch.tensor(10)
scalar
scalar.item()
print(type(scalar))

<class 'torch.Tensor'>


In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([1,2,3])
print(vector)
vector.ndim
# vector.size()
# vector.rank()


tensor([1, 2, 3])


1

In [6]:
vector.shape

torch.Size([3])

In [7]:
Matrix = torch.tensor([[1,2,3],[4,5,6]])
Matrix
Matrix.ndim
Matrix.shape

torch.Size([2, 3])

In [8]:
Matrix[0][1]

tensor(2)

In [9]:
Matrix.size()

torch.Size([2, 3])

In [10]:
TENSOR = torch.tensor([[[[1,2,3],
                          [4,5,6]],
                         [[5,6,7],
                          [8,9,10]]]])
TENSOR


tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 5,  6,  7],
          [ 8,  9, 10]]]])

In [11]:
TENSOR.shape

torch.Size([1, 2, 2, 3])

In [12]:
RandomTensor = torch.rand(2,3,4)
RandomTensor

tensor([[[0.1952, 0.6270, 0.6016, 0.3023],
         [0.4702, 0.7497, 0.1900, 0.5358],
         [0.5854, 0.0334, 0.8903, 0.2074]],

        [[0.5534, 0.8950, 0.2309, 0.0176],
         [0.3625, 0.6134, 0.0914, 0.9964],
         [0.7781, 0.3690, 0.9648, 0.7884]]])

In [13]:
RandomTensor.shape

torch.Size([2, 3, 4])

In [14]:
RandomTensor.ndimension()

3

In [15]:
RandomTensor.ndim

3

In [16]:
random_image_tensor = torch.rand(3, 224,  224)
random_image_tensor
random_image_tensor.shape

torch.Size([3, 224, 224])

In [17]:
random_image_tensor.ndim

3

In [18]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
one_to_twenty = torch.arange(0,20)
one_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [20]:
one_to_twenty.shape

torch.Size([20])

In [21]:
one_to_twenty.shape

torch.Size([20])

In [22]:
twenty_to_thirty = torch.zeros_like(one_to_twenty)
twenty_to_thirty

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
float_32 = torch.tensor([3,4,5], dtype=torch.float32, device='cpu', requires_grad=False)
print(float_32)
print(float_32.dtype)


tensor([3., 4., 5.])
torch.float32


In [24]:
float_16 = float_32.half()
print(float_16)
print(float_16.dtype)


tensor([3., 4., 5.], dtype=torch.float16)
torch.float16


In [25]:
print(torch.mul(float_16, float_32))

tensor([ 9., 16., 25.])


In [26]:
some_tensor = torch.randn(2, 3)
print(some_tensor)

tensor([[ 0.7946,  0.2328,  0.3964],
        [-1.2096,  0.6958,  1.3858]])


In [27]:
print(f"Tensor : {some_tensor}")
print(f"Device : {some_tensor.device}")
print(f"Shape : {some_tensor.shape}")
print(f"Type : {some_tensor.dtype}")


Tensor : tensor([[ 0.7946,  0.2328,  0.3964],
        [-1.2096,  0.6958,  1.3858]])
Device : cpu
Shape : torch.Size([2, 3])
Type : torch.float32


In [29]:
test_tensor = torch.tensor([1,2,3], dtype=torch.int32, device="cuda")
print(test_tensor)
print(f"Device : {test_tensor.device}")
print(f"Shape : {test_tensor.shape}")
print(f"Type : {test_tensor.dtype}")

tensor([1, 2, 3], device='cuda:0', dtype=torch.int32)
Device : cuda:0
Shape : torch.Size([3])
Type : torch.int32


In [30]:
torch.div(test_tensor, 10)

tensor([0.1000, 0.2000, 0.3000], device='cuda:0')

In [33]:
test_tensor / 10

tensor([0.1000, 0.2000, 0.3000], device='cuda:0')

In [34]:
!nvidia-smi


Thu Aug 13 07:28:29 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 596.49                 Driver Version: 596.49         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   54C    P8              2W /   62W |    1623MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [35]:
torch.cuda.is_available()

True

In [36]:
torch.cuda.device_count()

1

In [37]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [38]:
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [39]:
tensor = torch.tensor([1,2,3], device="cuda")
print(tensor , tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [40]:
tensor_on_cpu = tensor.cpu().numpy()
print(tensor_on_cpu)
print(tensor_on_cpu.device)
print(tensor_on_cpu.dtype)

[1 2 3]
cpu
int64


In [29]:
test_tensor = torch.tensor([1,2,3], dtype=torch.int32, device="mps")
print(test_tensor)
print(f"Device : {test_tensor.device}")
print(f"Shape : {test_tensor.shape}")
print(f"Type : {test_tensor.dtype}")

tensor([1, 2, 3], device='mps:0', dtype=torch.int32)
Device : mps:0
Shape : torch.Size([3])
Type : torch.int32


In [33]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([5,6])
print(tensor1)
print(tensor2)

tensor([1, 2, 3])
tensor([5, 6])


In [ ]:
tensor1.ndim


1

In [34]:
torch.matmul(tensor1, tensor2)
print(torch.matmul(tensor1, tensor2))

RuntimeError: inconsistent tensor size, expected tensor [3] and src [2] to have the same number of elements, but got 3 and 2 elements respectively